services:
  db:
    image: postgres:14
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    image: ${DOCKERHUB_USERNAME}/todo_backend:latest
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: todo_frontend
    restart: always
    image: ${DOCKERHUB_USERNAME}/todo_frontend:latest
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://todo_backend:8000  # Use internal Docker hostname
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run preview -- --host 0.0.0.0 --port 80

volumes:
  postgres_data:
